version: '3.8'

services:
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@db:5432/test
  #   develop:
  #     watch:
  #       - action: sync
  #         path: ./backend
  #         target: /src/backend
  #         ignore:
  #           - node_modules
  #       - action: rebuild
  #         path: package.json

  frontend:
    build:
      context: ./frontend
    ports:
      - '5173:5173'
    environment:
      - VITE_BACKEND_URL=http://backend:3000

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - '5432:5432'
